ALTER TABLE branches ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN version INT NOT NULL DEFAULT 1 CHECK (version>0),
  ADD COLUMN updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
ALTER TABLE invoices ADD COLUMN receipt_snapshot JSON NULL;
